config/routes.rb
ComedyHeadquarters::Application.routes.draw do

  root 'pages#home'

  get '/signin' => 'sessions#new', :as => 'sign_in'
  post '/sessions/create' => 'sessions#create'
  delete '/signout' => 'sessions#destroy', :as => 'sign_out'

  resources :votes

  resources :pictures

  resources :long_jokes

  resources :short_jokes

  resources :users

end

app/models/long_joke.rb
class LongJoke < ActiveRecord::Base
  belongs_to :user
end

app/controllers/long_jokes_controller.rb
class LongJokesController < ApplicationController
  before_action :set_long_joke, only: [:show, :edit, :update, :destroy]

  # GET /long_jokes
  # GET /long_jokes.json
  def index
    @long_jokes = LongJoke.all
  end

  # GET /long_jokes/1
  # GET /long_jokes/1.json
  def show
  end

  # GET /long_jokes/new
  def new
    @long_joke = LongJoke.new
  end

  # GET /long_jokes/1/edit
  def edit
  end

  # POST /long_jokes
  # POST /long_jokes.json
  def create
    @long_joke = LongJoke.new(long_joke_params)

    respond_to do |format|
      if @long_joke.save
        format.html { redirect_to @long_joke, notice: 'Long joke was successfully created.' }
        format.json { render action: 'show', status: :created, location: @long_joke }
      else
        format.html { render action: 'new' }
        format.json { render json: @long_joke.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /long_jokes/1
  # PATCH/PUT /long_jokes/1.json
  def update
    respond_to do |format|
      if @long_joke.update(long_joke_params)
        format.html { redirect_to @long_joke, notice: 'Long joke was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @long_joke.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /long_jokes/1
  # DELETE /long_jokes/1.json
  def destroy
    @long_joke.destroy
    respond_to do |format|
      format.html { redirect_to long_jokes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_long_joke
      @long_joke = LongJoke.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def long_joke_params
      params.require(:long_joke).permit(:contents, :user_id)
    end
end

app/helpers/long_jokes_helper.rb
module LongJokesHelper
end

app/views/long_jokes/_form.html.erb
<%= form_for(@long_joke) do |f| %>
  <% if @long_joke.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@long_joke.errors.count, "error") %> prohibited this long_joke from being saved:</h2>

      <ul>
      <% @long_joke.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :contents %><br>
    <%= f.text_area :contents, :size => "60x10" %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.select(:user_id, options_from_collection_for_select(User.all, :id, :name)) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/long_jokes/edit.html.erb
<h1>Editing long_joke</h1>

<%= render 'form' %>

<%= link_to 'Show', @long_joke %> |
<%= link_to 'Back', long_jokes_path %>

app/views/long_jokes/index.html.erb
<h1>Listing Long Jokes</h1>

<table>
  <thead>
    <tr>
      <th>Contents</th>
      <th>Author</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @long_jokes.each do |long_joke| %>
      <tr>
        <td><div style="width: 700px"><%= truncate(long_joke.contents, length: 300) %> <%= link_to 'View More', long_joke %></div></td>
        <td><div style="width: 200px"><%= long_joke.user.name %></div></td>
        <td><div style="width: 100px"><%= link_to 'Show', long_joke %></div></td>
        <td><div style="width: 100px"><%= link_to 'Edit', edit_long_joke_path(long_joke) %></div></td>
        <td><%= link_to 'Destroy', long_joke, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Long joke', new_long_joke_path %>

app/views/long_jokes/new.html.erb
<h1>New Long Joke</h1>

<%= render 'form' %>

<%= link_to 'Back', long_jokes_path %>

app/views/long_jokes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Joke:</strong>
  <%= @long_joke.contents %>
</p>

<p>
  <strong>Author:</strong>
  <%= @long_joke.user.name %>
</p>

<%= link_to 'Edit', edit_long_joke_path(@long_joke) %> |
<%= link_to 'Back', long_jokes_path %>